import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import CustomCursor from "@/components/ui/CustomCursor";


const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark" suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `(() => {
              const savedTheme = localStorage.getItem('theme');
              const theme = savedTheme === 'light' ? 'light' : 'dark';
              document.documentElement.classList.toggle('dark', theme === 'dark');
            })();`,
          }}
        />
      </head>
      <body
        className={`${poppins.className} antialiased bg-background text-foreground transition-colors duration-300`}
      >
        <CustomCursor />
        {children}
      </body>
    </html>
  );
}
